export const CLOUDSTART=()=>{

const START=`AUTORUN();BODIED();INSPECTION();URLCOLLECTOR();ZOOM();HOSTINGUPDATER();OPERATINGSYSTEM();UGANDANDISTRICITS();MONTHS();
`;

localStorage.setItem('RUN',START);

};